Repository jellyfin/jellyfin.org, pull requests merged in 2022-09, with the labels that each got.

#134 Home screen cleanup
  src/components/home/ClientSection.tsx
  src/components/home/HomepageFeatures.tsx
  src/png.d.ts
Labels: cleanup

#137 Fix downloads issues
  src/components/downloads/DownloadDetails.tsx
  src/data/downloads.tsx
Labels: bug

#145 Strictly check for Node 16 LTS and lockfile v3
  .npmrc
  package-lock.json
  package.json
Labels: cleanup

#136 Add In Action section to the home screen
  src/components/home/InActionSection.tsx
  src/pages/index.tsx
  static/images/screenshots/home/10.8-details.png
  static/images/screenshots/home/10.8-home.png
  static/images/screenshots/home/10.8-library.png
  static/images/screenshots/home/10.8-playback.png
Labels: enhancement

#148 Add new software freedom home screen section
  package-lock.json
  package.json
  src/components/home/BuiltByVolunteers.tsx
  src/components/home/FreeSoftware.tsx
  src/components/home/FreedomSection.tsx
  src/pages/index.tsx
  static/images/icons/people.svg
Labels: enhancement

#149 Use swiper pagination for screenshots
  docusaurus.config.js
  src/components/home/InActionSection.tsx
  src/css/custom.css
  src/css/swiper.css
Labels: enhancement

#152 Enable autoplay for screenshot slides
  src/components/home/InActionSection.tsx
Labels: enhancement

#157 Add markdownlint workflow
  .github/workflows/lint.yml
  .markdownlint.yaml
  blog/2021/04-12-mirrorbits-cdn.md
  docs/general/community-standards.md
Labels: github-actions

#162 General cleanup
  src/css/custom.css
  static/images/screenshots/home-10.7.png
Labels: cleanup

#164 Add sponsors to contribute page
  src/components/home/InActionSection.tsx
  src/pages/contribute.module.css
  src/pages/contribute.tsx
Labels: enhancement

#165 Disable search indexing of blog posts
  docusaurus.config.js
Labels: enhancement

#166 Fix links
  blog/2020/08-22-client-videotape/index.mdx
  docs/general/administration/installing.md
  docs/general/clients/codec-support.md
  docs/general/clients/index.md
  docs/general/server/storage.md
  src/components/common/DetailsCard.tsx
  src/components/downloads/DownloadDetails.tsx
  src/data/downloads.tsx
Labels: bug

#172 Add subtitle docs page redirect
  docusaurus.config.js
Labels: enhancement

#178 Use material icons from package
  src/components/common/PlatformIcon.tsx
  src/components/home/ClientSection.tsx
  static/images/icons/monitor.svg
  static/images/icons/plus-thick.svg
  static/images/icons/web.svg
Labels: cleanup

#180 Update the getting help documentation to reference the contact page
  docs/general/getting-help.md
Labels: enhancement

#181 Move storage docs to administration
  docs/general/administration/storage.md
  docusaurus.config.js
Labels: documentation, cleanup

#182 Port jellyfin-docs updates
  docs/general/administration/troubleshooting.md
  docs/general/clients/kodi.md
Labels: documentation

#179 Add CODEOWNERS for specific files
  .github/CODEOWNERS
Labels: enhancement

#186 Hide download cards missing unstable downloads
  src/components/downloads/DownloadDetails.tsx
  src/pages/downloads/index.tsx
Labels: enhancement

#189 Update clients page in docs
  docs/general/clients/index.md
  docs/general/clients/index.mdx
Labels: documentation, enhancement

#187 Combine download filters
  src/pages/downloads/index.tsx
Labels: cleanup

#184 Add client filtering options
  src/css/custom.css
  src/data/clients.ts
  src/data/platform.ts
  src/pages/clients/index.module.css
  src/pages/clients/index.tsx
Labels: enhancement

#200 Fix debian sources architecture
  src/data/downloads.tsx
Labels: bug, documentation
