Repository jellyfin/jellyfin.org, pull requests merged in 2022-10, with the labels that each got.

#202 Fix codec support page formatting
  docs/general/clients/codec-support.md
Labels: bug, documentation

#214 Revamp the about page and expand the fork story
  docs/general/about.md
Labels: hacktoberfest-accepted

#213 Adjust wording of several parts of the FAQ
  docs/general/faq.md
Labels: documentation

#217 Update docs with latest changes merged in jellyfin-docs
  docs/general/clients/codec-support.md
  docs/general/networking/apache.md
  docs/general/networking/fail2ban.md
  docs/general/server/media/movies.md
  docs/general/server/media/shows.md
Labels: documentation

#209 Add sass support
  .gitignore
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/common/DetailsCard.scss
  src/components/common/DetailsCard.tsx
  src/components/common/Hero.scss
  src/components/common/Hero.tsx
  src/components/contact/ContactCard.scss
  src/components/contact/DiscordCard.tsx
  src/components/contact/FacebookCard.tsx
  src/components/contact/IrcCard.tsx
  src/components/contact/MatrixCard.tsx
  src/components/contact/RedditCard.tsx
  src/components/contact/TelegramCard.tsx
  src/components/contact/TwitterCard.tsx
  src/components/home/CallToAction.module.scss
  src/components/home/CallToAction.tsx
  src/components/home/ClientSection.module.scss
  src/components/home/ClientSection.tsx
  src/components/home/FreedomSection.tsx
  src/components/home/HomepageFeatures.module.scss
  src/components/home/HomepageFeatures.tsx
  src/components/home/InActionSection.tsx
  src/components/home/LandingSection.module.scss
  src/css/custom.scss
  src/css/swiper.scss
  src/pages/clients/index.module.scss
  src/pages/clients/index.tsx
  src/pages/contribute.module.scss
  src/pages/contribute.tsx
  src/pages/downloads/index.module.scss
  src/pages/downloads/index.tsx
Labels: enhancement

#227 Remove announcement bar
  docusaurus.config.js
Labels: cleanup

#231 Remove reference to next.jellyfin.org in README
  README.md
Labels: documentation

#232 Add Swiftfin to client list
  src/components/clients/ClientDetails.tsx
  src/data/clients.ts
Labels: enhancement

#226 Add new website blog post
  blog/2022/10-18-new-website/index.mdx
Labels: enhancement, hacktoberfest-accepted

#234 Expand external file flag documentation
  docs/general/server/media/external-files.md
Labels: documentation

#228 Update site url configuration
  docusaurus.config.js
  static/CNAME
Labels: cleanup
