Repository jellyfin/jellyfin.org, pull requests merged in 2024-05, with the labels that each got.

#956 fix traefik v2.x doc: x-xss-protection description/value mismatch
  docs/general/networking/traefik2.md
Labels: documentation

#949 Add blog post for Release 10.9.0
  blog/2024/05-05-jellyfin-release-10.9.0/index.mdx
Labels: future-release

#784 docs: update to .NET 8
  docs/general/administration/configuration.md
  docs/general/contributing/development.md
  docs/general/installation/source.md
Labels: documentation, pre-release checklist, future-release

#926 doc: update macos install doc
  docs/general/installation/macos.md
Labels: documentation, pre-release checklist, future-release

#958 Update docker build instructions
  docs/general/installation/source.md
Labels: documentation, future-release

#933 fix: mark macOS bundle as custom ffmpeg ready
  src/data/downloads.tsx
  src/pages/downloads/server.tsx
Labels: pre-release checklist, future-release

#978 Update HWA docs for jellyfin-ffmpeg6
  docs/general/administration/hardware-acceleration/amd.md
  docs/general/administration/hardware-acceleration/intel.md
  docs/general/administration/hardware-acceleration/nvidia.md
Labels: documentation, cleanup, future-release

#875 feat: add hwa doc for apple platforms
  docs/general/administration/hardware-acceleration/apple.md
  docs/general/administration/hardware-acceleration/index.md
  docs/general/administration/hardware-selection.md
  docs/general/installation/macos.md
Labels: documentation, future-release
