Repository jellyfin/jellyfin.org, pull requests merged in 2024-02, with the labels that each got.

#845 Update some outdated HWA docs
  docs/general/administration/hardware-acceleration/amd.md
  docs/general/administration/hardware-acceleration/index.md
  docs/general/administration/hardware-acceleration/intel.md
  docs/general/administration/hardware-acceleration/nvidia.md
Labels: documentation

#856 Inform users of known issues in the latest Windows graphics drivers
  docs/general/administration/hardware-acceleration/amd.md
  docs/general/administration/hardware-acceleration/intel.md
Labels: bug, documentation

#863 Remove unraid reference
  docs/index.md
Labels: bug
